stages:
  - sync
  - build

sync_to_github:
  stage: sync
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "abenavid@redhat.com"
    - git config --global user.name "Alex Benavides"
    - |
      git remote add github https://$GITHUB_PAT@github.com/abenavid/mock-collection.git || \
      git remote set-url github https://$GITHUB_PAT@github.com/abenavid/mock-collection.git
    - git fetch --all
    - git checkout -B main origin/main
    - git push --force github main
  tags:
    - internal
    - pah

# build_mock_collection_2:
#   stage: build
#   script:
#     - apt-get update && apt-get install -y python3 python3-pip
#     - pip3 install ansible-core
#     - mkdir -p output
#     - echo "Building collection for mock_namespace_2/mock_collection_2..."
#     - if [ -d "mock_namespace_2/mock_collection_2" ]; then
#         cd mock_namespace_2/mock_collection_2 || exit 1;
#         ansible-galaxy collection build --output-path=../../../output --force || echo "Collection build failed for mock_namespace_2/mock_collection_2!";
#         cd - || exit 1;
#       else
#         echo "Directory mock_namespace_2/mock_collection_2 does not exist!";
#         exit 1;
#       fi
#     - echo "Build complete. Output contents:"
#     - ls -al output
#   artifacts:
#     paths:
#       - output/*.tar.gz
#     expire_in: 1 week
#   tags:
#     - internal
#     - pah
