stages:
  - sync

sync_from_github:
  stage: sync
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "abenavid@redhat.com"
    - git config --global user.name "Alex Benavides"
    - git remote add github https://$GITHUB_PAT@github.com/abenavid/mock-collection.git
    - git fetch github
    - git merge github/main --allow-unrelated-histories
    - git push origin main
  tags:
    - internal
    - pah
