stages:
  - sync

sync_from_github:
  stage: sync
  script:
    - apt-get update && apt-get install -y git
    - git config --global user.email "abenavid@redhat.com"
    - git config --global user.name "Alex Benavides"
    - git remote set-url origin https://$GITLAB_PAT@gitlab.consulting.redhat.com/internal-ansible-library/test.git
    - git fetch origin
    - git checkout -B main origin/main
    - git merge github/main --allow-unrelated-histories
    - git push origin main
  tags:
    - internal
    - pah
